services:
  # 1. Main Application (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      REDIS_URL: ${REDIS_URL}
      MAILER_DSN: ${MAILER_DSN}
    command: php-fpm
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  # 2. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "8000:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  # 3. Worker (Async Job Consumer)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      REDIS_URL: ${REDIS_URL}
    command: php bin/console messenger:consume async -vv
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  # 4. Scheduler (Cron Replacement)
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      REDIS_URL: ${REDIS_URL}
    command: php bin/console messenger:consume scheduler_monitoring scheduler_telemetry -vv
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  # 5. Telemetry Ingestor (High Volume Consumer)
  telemetry-ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      REDIS_URL: ${REDIS_URL}
    command: php bin/console messenger:consume telemetry -vv
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  # Infrastructure Services
  # In a real production environment, you might use Managed Databases.
  # For this setup, we host them in Docker.

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
